[build]
  functions = "src/netlify-functions"

[context.production.environment]
  NODE_VERSION = "14" # Specify the Node.js version you need
  DATABASE_URL = "mongodb+srv://username:password@cluster.mongodb.net/dbname" # Add your production DB URL
